---
- name: Stop HAProxy service
  service:
    name: haproxy
    state: stopped
  notify: restart heartbeat

- name: Disable HAProxy service
  service:
    name: haproxy
    enabled: no
  notify: restart heartbeat

- meta: flush_handlers

- name: Wait for haproxy to become ready
  shell: curl -k -L --head https://{{ OS_FLOATIP }}
  register: result
  until: result.stdout.find("200 OK") != -1
  retries: 60
  delay: 5
  connection: local
  sudo: false