---
- name: Stop HAProxy service
  service:
    name: haproxy
    state: stopped
  notify: restart heartbeat

- name: Disable HAProxy service
  service:
    name: haproxy
    enabled: no
  notify: restart heartbeat
