---
- name: Stop HAProxy service
  service:
    name: haproxy
    state: stopped
  notify: restart heartbeat

- name: Disable HAProxy service
  service:
    name: haproxy
    enabled: no
  notify: restart heartbeat

- meta: flush _handlers

- name: Wait for haproxy to become ready
  wait_for:
    host: "{{ OS_FLOATIP }}"
    port: 443
  connection: local
  sudo: false
